import type { Prisma } from '@prisma/client'
import { getKolkataDateString } from '@/lib/date-utils'
import { nextSequentialNumber } from '@/lib/stock'
import {
  DAILY_PROCUREMENT_STATUS,
  DAILY_SUPPLY_ORDER_STATUS,
  buildDocumentReference,
  roundMoney,
} from '@/lib/daily-procurement'
import { DAILY_CONVERSATION_STATUS, PROCUREMENT_MESSAGE_TYPE } from '@/lib/daily-conversations'

type Tx = Prisma.TransactionClient

async function nextSupplyOrderNumber(tx: Tx, offset: number) {
  const date = getKolkataDateString().replace(/-/g, '')
  const prefix = `DSO-${date}`
  const count = await tx.dailySupplyOrder.count({ where: { orderNumber: { startsWith: prefix } } })
  return `${prefix}-${String(count + offset + 1).padStart(3, '0')}`
}

export async function generateConversationSupplyOrders(tx: Tx, batchId: string, actor: { id: string; name: string }) {
  const batch = await tx.dailyProcurementBatch.findUnique({
    where: { id: batchId },
    include: {
      conversations: {
        include: {
          supplier: true,
          lines: { include: { batchLine: true, item: true } },
          supplyOrders: { include: { lines: true } },
        },
      },
    },
  })
  if (!batch) throw new Error('Daily Procurement Requirement not found')

  const createdOrders: any[] = []
  let offset = 0
  for (const conversation of batch.conversations) {
    const confirmedLines = conversation.lines.filter((line) => line.confirmedQty > 0 && line.status !== 'CANCELLED')
    if (!confirmedLines.length) continue

    const existing = conversation.supplyOrders.find((order) => order.status !== DAILY_SUPPLY_ORDER_STATUS.CANCELLED)
    if (existing) {
      createdOrders.push(existing)
      continue
    }

    const totalAmount = roundMoney(confirmedLines.reduce((sum, line) => sum + line.confirmedQty * (line.vendorRate ?? 0), 0))
    const poNumber = await nextSequentialNumber(tx, 'purchaseOrder', `DPO-${getKolkataDateString().replace(/-/g, '')}`)
    const purchaseOrder = await tx.purchaseOrder.create({
      data: {
        poNumber,
        supplierId: conversation.supplierId,
        status: 'APPROVED',
        totalAmount,
        approvedBy: actor.id,
        approvedAt: new Date(),
        autoGenerated: true,
        internalOnly: true,
        sourceType: 'DAILY_PROCUREMENT',
        expectedDeliveryDate: batch.deliveryDate,
        deliveryDate: batch.deliveryDate,
        createdBy: actor.name,
        notes: `Internal receiving document for Daily Procurement ${batch.batchNumber}`,
        items: {
          create: confirmedLines.map((line) => ({
            itemId: line.itemId,
            qty: line.confirmedQty,
            unitPrice: line.vendorRate ?? 0,
          })),
        },
      },
    })

    const orderNumber = await nextSupplyOrderNumber(tx, offset++)
    const supplyOrder = await tx.dailySupplyOrder.create({
      data: {
        orderNumber,
        batchId: batch.id,
        supplierId: conversation.supplierId,
        conversationId: conversation.id,
        purchaseOrderId: purchaseOrder.id,
        status: DAILY_SUPPLY_ORDER_STATUS.CONFIRMED,
        whatsappReference: buildDocumentReference('DSO', batch.batchNumber),
        messageStatus: 'DRAFT',
        businessConfirmationStatus: 'CONFIRMED',
        deliveryLocation: batch.deliveryLocation,
        deliveryDate: batch.deliveryDate,
        deliveryTimeSlot: batch.deliveryTimeSlot,
        createdBy: actor.name,
        approvedBy: actor.name,
        approvedAt: new Date(),
        confirmedById: actor.id,
        confirmedAt: new Date(),
        confirmationSource: 'WHATSAPP_OR_MANUAL_REVIEW',
        lines: {
          create: confirmedLines.map((line) => ({
            itemId: line.itemId,
            itemName: line.item.name,
            orderedQty: line.confirmedQty,
            unit: line.batchLine.unit,
            rate: line.vendorRate,
            status: 'ORDERED',
          })),
        },
      },
      include: { supplier: true, lines: true },
    })

    await tx.dailyConversationLine.updateMany({
      where: { id: { in: confirmedLines.map((line) => line.id) } },
      data: { status: 'READY_FOR_RECEIVING' },
    })
    await tx.dailyProcurementConversation.update({
      where: { id: conversation.id },
      data: { status: DAILY_CONVERSATION_STATUS.READY_FOR_RECEIVING },
    })
    await tx.whatsAppMessage.create({
      data: {
        phone: conversation.normalizedPhone,
        message: `Supply confirmed for ${batch.batchNumber}. Receiving is ready against ${orderNumber}.`,
        rawMessage: `Supply confirmed for ${batch.batchNumber}. Receiving is ready against ${orderNumber}.`,
        direction: 'SYSTEM',
        status: 'PROCESSED',
        messageType: PROCUREMENT_MESSAGE_TYPE.SYSTEM_EVENT,
        senderName: 'Inventra',
        supplierId: conversation.supplierId,
        dailyBatchId: batch.id,
        dailyConversationId: conversation.id,
        verificationStatus: 'VERIFIED',
      },
    })
    createdOrders.push(supplyOrder)
  }

  await tx.dailyProcurementBatch.update({
    where: { id: batch.id },
    data: {
      status: DAILY_PROCUREMENT_STATUS.APPROVED,
      approvedBy: actor.name,
      approvedAt: new Date(),
      version: { increment: 1 },
    },
  })
  return createdOrders
}
