import type { Prisma } from '@prisma/client'
import { randomBytes } from 'crypto'
import { getKolkataDateString } from './date-utils'
import { OPEN_PO_STATUSES } from './po-status'

export interface ReorderItem {
  stock: number
  reservedQty: number
  minStock: number
  reorderQty: number
  preferredSupplierId: string | null
}

/**
 * Pure decision: should this item trigger an auto-PO right now?
 * True only when available stock (stock - reserved) has fallen to/below minStock,
 * a reorder qty is configured, a preferred supplier is set, and no PO is already open.
 */
export function shouldReorder(item: ReorderItem, hasOpenPo: boolean): boolean {
  if (hasOpenPo) return false
  if (item.reorderQty <= 0) return false
  if (!item.preferredSupplierId) return false
  return item.stock - item.reservedQty <= item.minStock
}

type Tx = Prisma.TransactionClient

/**
 * After a stock-decreasing op, auto-create a DRAFT purchase order for an item that
 * has hit its reorder threshold — unless an open PO already covers it. Reuses the
 * existing PurchaseOrder + POItem models. Call inside the same transaction as the
 * stock change so it sees post-decrement quantities.
 */
export async function checkReorder(tx: Tx, itemId: string): Promise<void> {
  const item = await tx.item.findUnique({ where: { id: itemId } })
  if (!item || item.deletedAt || !item.active) return

  const openPo = await tx.pOItem.findFirst({
    where: { itemId, purchaseOrder: { status: { in: [...OPEN_PO_STATUSES] } } },
  })

  if (
    !shouldReorder(
      {
        stock: item.stock,
        reservedQty: item.reservedQty,
        minStock: item.minStock,
        reorderQty: item.reorderQty,
        preferredSupplierId: item.preferredSupplierId,
      },
      !!openPo,
    )
  ) {
    return
  }

  const date = getKolkataDateString().replace(/-/g, '')
  // Random suffix (not a row count): checkReorder runs inside the stock-out
  // transaction, so a duplicate poNumber would throw P2002 and roll back the
  // entire issue/checkout/transfer — failing a legitimate operation under any
  // concurrency. A random token makes that collision negligible.
  const poNumber = `PO-AUTO-${date}-${randomBytes(4).toString('hex')}`
  const unitPrice = Math.max(0, Math.round(item.price || 0))

  await tx.purchaseOrder.create({
    data: {
      poNumber,
      supplierId: item.preferredSupplierId!,
      status: 'DRAFT',
      autoGenerated: true,
      totalAmount: unitPrice * item.reorderQty,
      notes: `Auto-generated: "${item.name}" hit reorder threshold`,
      items: { create: [{ itemId, qty: item.reorderQty, unitPrice }] },
    },
  })
}
