'use strict'

import { useEffect, useRef } from 'react'
import { toast } from 'sonner'
import { useAppStore } from '@/lib/store'
import { api } from '@/lib/api'

export function BarcodeListener() {
  const { setCurrentView, flags } = useAppStore()
  const buffer = useRef<string>('')
  const lastKeyTime = useRef<number>(0)

  useEffect(() => {
    // Only active when barcode feature flag is enabled
    if (!flags.barcode) return

    const handleKeyDown = (e: KeyboardEvent) => {
      const now = Date.now()

      if (now - lastKeyTime.current > 50 && buffer.current.length > 0) {
        buffer.current = ''
      }
      lastKeyTime.current = now

      if (e.key === 'Shift' || e.key === 'Control' || e.key === 'Alt' || e.key === 'Meta') return

      if (e.key === 'Enter') {
        if (buffer.current.length > 3) handleScan(buffer.current)
        buffer.current = ''
        return
      }

      if (e.key.length === 1) buffer.current += e.key
    }

    const handleScan = async (code: string) => {
      // Handle QR codes generated by this app: storehub:<itemId>
      if (code.startsWith('storehub:')) {
        const itemId = code.slice('storehub:'.length)
        try {
          const res = await api.items.list({ pageSize: 1 })
          // Look up item directly
          const itemRes = await fetch(`/api/items/${itemId}`, {
            credentials: 'include',
          })
          if (!itemRes.ok) {
            toast.error('Item not found for scanned code')
            return
          }
          const { item } = await itemRes.json()
          const available = item.stock - item.reservedQty
          toast[available === 0 ? 'error' : available <= item.minStock ? 'warning' : 'success'](
            `📦 ${item.name}`,
            {
              description: `Stock: ${item.stock} | Reserved: ${item.reservedQty} | Available: ${available} ${item.unit}`,
              action: {
                label: 'View',
                onClick: () => setCurrentView('store-item-master'),
              },
              duration: 6000,
            }
          )
        } catch {
          toast.error(`Could not look up scanned item`)
        }
        return
      }

      // Legacy HUB- format
      if (code.startsWith('HUB-')) {
        toast.info(`Scanned: ${code}`, { description: 'Navigating to inventory…' })
        setCurrentView('store-item-master')
        return
      }

      toast.info(`Unknown scan: ${code}`)
    }

    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [setCurrentView, flags.barcode])

  return null
}
